### ISSUE TITLE
Add the ability to more safely accept unsafe file attachments in submissions

### ISSUE THREAD

**Issue by danblah** [HyphaApp/hypha#1052]
Possible enhancements
- Create/get/save an md5 hash of any file attachments within submissions
- Make an call with the file hash to VirusTotal's api (or something similar/better that doesnt have the permissive sample license)
- If no existing report, upload file to receive report
- Until report, do not let anyone download the file (grey it out or something)
- If report comes back clean, allow download
- If report comes back unclean, don't allow download (show it as red, link to or display report findings)
- Create a role that is allowed to download these files and if viewing, submission, give them that option
- Allow doc/docx/xls/xlsx files

Open questions...
* Should we only post samples for unsafe file types?
* How do we make it clear to folks that if they use an unsafe file type, it will be uploaded to a 3rd party?
* Are there good VT alternatives we could use without the same sample lic they have?
* What else?

**Comment by Erioldoesdesign** [comment]
Q1 2022 Rebasing updates:
* Removed open or close label
* This is not a single issue, it's more of an Epic/META. - **PM needed to build out Epic/META details**
* Added 'Partner:OTF' label
* Also think this is a dev spike first thoughts @frjo  ?
* This is about supporting applicants that are unaware of unsafe file types so that might mean they are high risk.
* Size estimated at XL
* Pretty sure this could be on **OTF** roadmap re. High risk users and improving security.
* Removed from dev backlog board: https://github.com/HyphaApp/hypha/projects/2 (because it needs design and research before development!)

**Comment by fourthletter** [comment]
On June 6 - FJ + DL discussed clearer instructions or parameters for applicants on submission forms when they need to upload documents. Currently instuctions to applicants are for PDF files.
