### ISSUE TITLE
Changes to the Meta category Selection interface, Meta Categories admin interface and term edit page

### ISSUE THREAD

**Issue by danblah** [HyphaApp/hypha#1284]
See https://test-apply.opentech.fund/admin/categories/metacategory/

On the edit page, create an archive link/button that sits between edit and delete. Archive does not delete the term but makes it unavailable as a selectable/filterable option, displays as lighter greyed out listing in the admin page, and has an unarchive option when archived. Ideally, archive terms are not in api results (unless specifically asked for). If trivial, make a display option on the admin page that unhides archived items (where they are hidden by default).

Make delete only an option available to users in role Admin

Within the term's edit page ([example](https://test-apply.opentech.fund/admin/categories/metacategory/edit/3/)), ror each term, offer these fields within an options header:
* Help text (text field, that allows richtext & urls)
* Make available to filter on dashboard (check box) 
* Make available for applications (check box)

How are terms currently ordered? What are ways we could control how they are ordered?

**Comment by Parbhat** [comment]
Meta categories are currently ordered by name. Do we need custom order?

> Make delete only an option available to users in role Admin

Permission to view/delete is available to admin by default. Groups can be given access to view/edit/delete if required via Settings > Group in the admin area.

Created PR #1301 for archive and other options.

**Comment by Parbhat** [comment]
Changes from Issue https://github.com/OpenTechFund/opentech.fund/issues/972#issuecomment-515439839

* Rename Meta Categories to Meta Terms
* Within the submission page's Meta Categories block, Show the top-level categories that the selected ones are within (where the top-level Car is bolded as a header for Saab, Demographics for Gender/Young, etc). If this can be done before going to live quickly, lets do that and deploy to live.
* In the submissions page, in the add tag form, if you backspace once, it removes all the tags (rather than just the next one)
* If you select a term once (say lion), then try to select it again, it deletes all other tags in the list.
* Cat is listed twice and should be only listed once.
* It's not clear that next categories are actually nested in the selection interface. For example, in the selection interface, Animal and Cat (the bolded ones) appear to be the same hierarchical level. Can items under other items be indented/bolded/italicized to make it clear they are under a higher-level term?

**Comment by fourthletter** [comment]
related to https://github.com/HyphaApp/hypha/issues/2745
