### ISSUE TITLE
Field group wagtail admin ui and nested field groups

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#1355]
1. The field groups work well but are hard to setup for staff. Getting confusing with the end field that is easy to forget and find amount all the fields. A new UI where it's very obvious what fileds are part of a group and not with out the need fo a special end field.
2. Ability to nest field groups would be really nice to have.
3. Ability to have one trigger field with 2 or more options that opens corresponding field groups. Click option one and field group one opens, click option four and field group four opens.

**Comment by frjo** [comment]
@Parbhat  How feasible are these three enhancements?

The first we have talked about before and we decided to start with the more simple way but it's not working out for OTF staff. 

Two I think we also bruched when we first implemented this. How time consuming would it be?

The third is new and to me in sounds difficult to have one type of field group that can cover all the feature?

**Comment by Parbhat** [comment]
@frjo Agree, the current interface to create groups in admin is not good. Reimplementing Application form fields grouping using [stream block](http://docs.wagtail.io/en/v2.5.1/topics/streamfield.html#streamblock) should be a good way as mentioned in issue #1259. Using a stream block will probably solve issue 1 and 3. Clicking on new group block will display a new set of form field choices (same to the initial fields list). As the fields are now nested, we will need to update code to create form fields [dict](https://github.com/OpenTechFund/opentech.fund/blob/767de79cc46550939055576e7c554054e1d3eabc/opentech/apply/stream_forms/models.py#L17) from nested form fields, check single-use/required fields etc. Maybe we can create an initial prototype to test and see if we want to go with it further.

Simplest solution to 1 will be to tweak/override the default streamfield styles in admin similar to styling [performed](https://github.com/OpenTechFund/opentech.fund/pull/1295) in frontend. Also, we can have additional checks in the admin. So that admin user can not save the form if the group start block is present and end block is not.

**Comment by fourthletter** [comment]
Related to https://github.com/HyphaApp/hypha/issues/2798
