### ISSUE TITLE
Document deleting Sections or Questions from Round Applications

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#1630]
We want to delete a question or section from round applications. How could I do this while also preserving historical data? 

Is it as simple as deleting a section or question from the current Round and application? Are there other steps? Should I consider potential ramifications from this action?

**Comment by frjo** [comment]
Applicants that already have submitted an application will continue using the old version of the form, the form is saved with each application.

Only new applications will use the new form.

Also if you want this change in future rounds you need to make the change in the form attached to the fund as well.

Do OTF not have this documented? Questions how funds/rounds/application forms works seems to come up regularly.

If it's not documented (or badly documented) this really should be fixed!

It is a bit complex, but that is because OTF laid down some very specific demands for how it should work.

**Comment by todd-dembrey** [comment]
We created the following document just before launch - it is missing a clear instructions on how to alter running rounds which we should address, but it is mentioned in places. 

https://docs.google.com/document/d/1Oq9dBTU0q-HSpb91wpHHq96LrxeL9pACbSYzu6ELyrs/edit?usp=sharing

I do need to add some more documentation around the core behaviour of the app generally so perhaps this is something that can be addressed there?

**Comment by saoun** [comment]
@todd-dembrey is this something that you can add to the documentation? That would be great

@fourthletter, separately, do we not have any type of documentation about rounds? If not, can you start a document that's mostly FAQs for now, and add those types of questions (like the one you just asked), and Fredrik's answer? And we can keep populating.

**Comment by saoun** [comment]
@fourthletter hopefully this is something that will be addressed by @todd-dembrey in the current sprint. In the meantime, do we have any user guides for this? for staff members?

**Comment by fourthletter** [comment]
@saoun We currently have documentation about rounds and other web app issues.

**Comment by saoun** [comment]
could you add a FAQ section to that doc that would include questions like this one, to start with? @fourthletter

**Comment by fourthletter** [comment]
@saoun The information fred provided was added to the instruction manual back in October 2019.
