### ISSUE TITLE
Assign reviewer and partner roles with mobile browser

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#1758]
- Any personally identifying information: Gal-on-the-go

**Is your feature request related to a problem? Please describe.**
I currently can't assign reviewers or partners to an application on the mobile app. This feature is useful to ensure staff could do work in a timely manner.

**Is your feature request related to an existing functionality? Please describe.**
This feature exists and functions on other devices.

**My device**
I am using an android

**Priority**
- Medium (slowing you down)

**Affected roles**
- Staff
- Applicants
- Reviewers
- Partners

**Comment by frjo** [comment]
To be really nit picky, there is no "mobile app". What you see on a mobile phone is the same web site that you see on your computer. We have rules in the styles (css) that make the site look different for large and big screens.

If you make the browser window really narrow on your computer you will see more or less how it looks on mobile.

When testing I find the forms under "Actions to take +". For some reason the select boxes does not work when I access with Safari on my iPhone.

Will need to investigate this. I label this as a bug since it's something that should work.

**Comment by frjo** [comment]
If you put your phone in landscape orientation the select fields work. But you then do not see the complete form.
