### ISSUE TITLE
Create a db flowchart for Hypha

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#1962]
A tool like http://schemaspy.org/ might be useful.

**Comment by harumhelmy** [comment]
Currently exploring SchemaCrawler for this -- https://github.com/schemacrawler/SchemaCrawler/releases

**Comment by harumhelmy** [comment]
Sorry for the delay on this! Here's [Hypha's schema ](https://drive.google.com/file/d/14k95lbJoTdzT_953CGo7p4VD4vCYHdsN/view?usp=sharing)in its entirety, generated with SchemaCrawler. I output it in a PDF so that you can easily search the file's text. 

It's huge (as you probably already know, hehe) but if we ever need to visualize just chunks of it, SchemaCrawler could likely do that. It's a CLI tool with pretty good documentation of all of its features once you get everything going (how to set it up was a little less obvious!).

@frjo, let me know what you'd like next -- happy to write up some quick instructions on how to use the tool if you think that would be helpful, or figure out how to generate a different kind of visualization of the schema (e.g. just parts of it or show the schema in smaller chunks).

**Comment by frjo** [comment]
Added the PDF directly here on gitHub: [hypha-schema.pdf](https://github.com/OpenTechFund/hypha/files/4675830/hypha-schema.pdf)

**Comment by frjo** [comment]
@harumhelmy A wiki page with instructions to build the schema PDF would be excellent!
