### ISSUE TITLE
Changes to the review form rating streamfield

### ISSUE THREAD

**Issue by danblah** [HyphaApp/hypha#2149]
Changes I need asap:

- [ ] Move the rating above the text field
- [ ] Do not make the text field required (only require the rating)
- [ ] Apply these to existing/active review forms we're using at Reset :-/

How quickly can we implement these @frjo and @Parbhat?

Changes I'd like to also see but not as critical:

- [ ] Text field collapsed by default, expandable via an "Add comment" click
- [ ] Ability to require text field input
- [ ] Ability to specify whether the comment field is expanded or collapsed by default.

**Comment by Parbhat** [comment]
@danblah These changes can be implemented in a few days. Not sure if you know but we also recently added a score field which allows adding score without the text field. So, only the rating will be visible. Does the new field (score without text) will be sufficient or we should implement the above requirements?

<img width="947" alt="Screen Shot 2020-10-29 at 11 43 40 AM" src="https://user-images.githubusercontent.com/4817493/97532445-5edd6800-19dc-11eb-9207-d84820c875b1.png">

**Comment by danblah** [comment]
Yes! This works great. Could we add "Group fields" and "Group fields end" to review forms quickly? If so, I could add a "Would you like to provide a comment?" Yes/no and expose a text input if yes. This would resolve the whole ticket then.

**Comment by danblah** [comment]
CAN SOMEONE PLEASE LEFT ALIGN THE "See help guide for more information." TEXT ON THE RESET REVIEW FORMS OMG I HATE IT PLEASE PLEASE FIX!??

**Comment by Parbhat** [comment]
Implementing the issue requirements will be simpler than Grouping functionality in review forms. Can you add a screenshot for "See help guide for more information"? Is it on application or review forms? Application forms are showing it correctly in separate line. Maybe a separate issue would be better.

**Comment by frjo** [comment]
See https://github.com/OpenTechFund/hypha/issues/2051

**Comment by sks444** [comment]
> Move the rating above the text field

This is not configurable so if we implement this it will also change all the existing review forms. Just wanted to make sure if that is okay with both OTF and Reset.

We would also need to handle to types of data for edit/detail forms as earlier we were saving it as [comment, score].

> Do not make the text field required (only require the rating)

We had an [issue](https://github.com/OpenTechFund/hypha/issues/2053) regarding this, and [discussed the problems](https://github.com/OpenTechFund/hypha/issues/2053#issuecomment-660922808) in making only the rating field required instead of text. So we implemented ScoreWithoutTextBlock as an alternative.

> Text field collapsed by default, expandable via an "Add comment" click

Given the above reason. Even if we implement the text field collapsing functionality, it would be of no use when score block is required as anyway we would need a value for the text field.

--- 
We just had an idea of having a block to display only input box, which can be set to hidden/shown and if hidden can be shown by clicking of a button on the form. Which could be used after ScoreWithoutTextBlock. 

But not currently sure about this as it could take time and planning.

**Comment by Parbhat** [comment]
@ei8fdb Is it okay to shift score field above text field of Score block in review forms? The change is requested by Reset. Should we make it default and change for both OTF and Reset. Currently, first text input is shown and then the score field.

<img width="813" alt="Screen Shot 2020-11-03 at 3 36 07 PM" src="https://user-images.githubusercontent.com/4817493/97972346-5fb23780-1dea-11eb-9335-1225d959eeb3.png">

**Comment by ei8fdb** [comment]
@Parbhat The ideal would be to make this user configurable. So, Reset can configure it in the way that makes sense to them, and OTF could stay with the current default.

Is that possible?

**Comment by Parbhat** [comment]
@ei8fdb Thanks, there are some constraints to make it user-configurable. The new approach may be suitable for both OTF and Reset as showing score first makes more sense.
