### ISSUE TITLE
[Meta] Ability for managers and applicants to turn on/off different kinds of notifications, choose which channel they receive notifications, and manually adapt text of notifications

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#2161]
As a <user> I want to Hypha to send me notifications when important statuses are triggered so that I can do the right thing.

## Minimum Viable Product
Right now, we're waiting for some feedback from others on what types of notifications are needed and what they should apply to, so we'll start with this notification:
- [ ] 5 days before the current round closes and if no new round exists, Hypha sends an email with a message.

Message subject:
> Current round closes in 5 days. No new round exists.

Message body:
> Dear $NAME,
> 
> $FUNDNAME $ROUNDNAME is currently open and will close in 5 days. No new round exists. You should [create the next round](https://link-to-creating-the-next-round-for-the-fund.com)."

When the user clicks on the "[create the next round](https://link-to-creating-the-next-round-for-the-fund.com)" link, it brings them to the page in Wagtail to create the new round.

**Comment by ei8fdb** [comment]
These notifications are part of a bigger product design question: what notifications does the user need from Hypha?

**Comment by fourthletter** [comment]
@ei8fdb here is a [document to highlight communication and notification challenges](https://docs.google.com/spreadsheets/d/1S-X8yp8ltN3_rnfryZOxeO81DFCWQmzMtFsqGVOOgzE/edit#gid=1910522872). It's a start, but will mostly likely require a deeper dive.

**Comment by fourthletter** [comment]
related to #2225

**Comment by ei8fdb** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Hypha notifications](https://trello.com/c/If6nzQ59/21-hypha-notifications)

**Comment by fourthletter** [comment]
Here is a compilation of email & slack communication/notifications to applicants and staff: https://docs.google.com/document/d/1Y2oZWvrysBO9OjuoPbviI-UruUnib9P6TkBWHgam_Is/edit#

**Summary**
Who receives these notifications?
- Applicants receive approximately 5 automated emails related to workflow status change
- Applicants also receive bespoke communication within Hypha. They are notified with an email letting them know that a message is waiting for them within Hypha. 
- 'Lead' receives notifications via slack regarding all adjustments related to the fund/round
- Reviewer receives notification when a review has been submitted, and the reviewer can no submit their review
- AC (external reviewer) do NOT receive automated emails.

What notifications are needed?
- Staff receive notifications when a new application has been submitted, 

Notifications Funds:
The current round is due to close soon.
The current round is closing soon and no new round exists. (This one is the first that @danblah requested)
The next round is due to open soon.
Others?

**Comment by fourthletter** [comment]
related to https://github.com/HyphaApp/hypha/issues/2704

**Comment by fourthletter** [comment]
closing because of epic https://github.com/HyphaApp/hypha/issues/2812
