### ISSUE TITLE
Rename Screening status to Screening Decisions (confusing with Workflow status/state)

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#2208]

**Comment by chriszs** [comment]
We got the same feedback about it being confusing how it interacts with workflow status. In our case, there's some org-specific terminology that ARDC uses ("eligibility review," "eligible," "ineligible") that they'd prefer and that we'll implement with an org-specific locale. The issue is that the functionality seems to overlap with workflow status regardless of the name.

**Comment by fourthletter** [comment]
The workflow status where program staff make intial assessments could be called "**Initial Intake**" in Hypha so we can keep all verbiage screening statuses everywhere else.


### Screening Statuses (WagTail)
![Screenshot 2022-06-04 7 34 41 PM](https://user-images.githubusercontent.com/20019656/172018949-aa188a20-8ee2-4f21-be94-6fd72b27776b.png)

### Screening Reasons(React App)
![Screenshot 2022-06-04 7 36 32 PM](https://user-images.githubusercontent.com/20019656/172019014-9c7bd827-e2a8-4c2d-aab2-7f723a2d2223.png)

### Screen Application or Screening Options (Submission View)
![Screenshot 2022-06-04 7 36 03 PM](https://user-images.githubusercontent.com/20019656/172019030-4ac59e61-bb65-4643-91fc-9eea98780daa.png)

**Comment by fourthletter** [comment]
![Screenshot 2022-09-26 4 25 56 PM](https://user-images.githubusercontent.com/20019656/192302100-6c035ef6-0b06-419d-a0c7-9f3c65bf4905.png)
