### ISSUE TITLE
Project table filters has broken drop downs

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#2388]
The project table filters at https://test-apply.hypha.app/apply/projects/ has broken drop downs. Compeer with https://test-apply.hypha.app/apply/submissions/all/.

Most likely a update to filters and/or select2 that has not been implemented.

**Comment by sandeepsajan0** [comment]
I thought I should provide just an update at least.
**Update**: I looked into it, and I found it is not specific to Projects filter. Actually, it is happening everywhere, where we are using the same filter fields multiple times on the same page(ex: fund). In fact, select2 media is getting overwritten for upper filters by lower filters. 

Ex: [In here](https://test-apply.hypha.app/apply/projects/) Projects' fund, status, and lead filter's media is getting override by PaymentRequest fund, status, and lead filter's media. I checked it by [reordering here](https://github.com/HyphaApp/hypha/blob/main/hypha/apply/projects/templates/application_projects/overview.html#L46) as PaymentRequest and Project then the PaymentRequest filters were not working. 
And it is working fine s[there](https://test-apply.hypha.app/apply/projects/all), because there are no other filters to override it. 

I am working to avoid this overridden problem.
Thanks
