### ISSUE TITLE
Create a new "Finance" user role with their own Hypha view

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#2389]
Set up "is_finance" similar to "is_apply_staff". They should only have access to project part of Hypha.

They need a dashboard that shows a table of invoices that have been approved by staff but not by finance.

I think we can reuse the table that is shown on the staff dashboard. We have some updates for that table in another issue.

The project page, the invoices and reports, uploaded files (PDF invoices etc.) and the project communication tab.

They will mostly use Hypha to talk with staff via the communication tab when invoices need corrections.

## UI Design Demo

- [ ] record new demo

## UI Designs

When the finance user logs in they see their dashboard - by default it shows the invoices that need to be reviewed.
![4 1 - default view when they log in](https://user-images.githubusercontent.com/1899506/124264183-743eff00-db34-11eb-8692-114516b937bb.png)

If Yodit wants to see all the invocies, she clicks on "Show all invoices", which brings her to the next screen:

The view of "Show all invoices" - 
![4 2 - view to show all invoices with all statuses](https://user-images.githubusercontent.com/1899506/124264216-802ac100-db34-11eb-87b6-2052010975dc.png)
If Yodit needs to see projects, she clicks on "Projects".

Project statuses shown in this view are for projects that have been funded, are being funded, or will be funded.
![4 3 - all projects view](https://user-images.githubusercontent.com/1899506/124264260-8a4cbf80-db34-11eb-8be2-7666cd3a4934.png)

If Yodit the finance user needs to see a specific project, she clicks on the project name, e.g. Maya Summit, which brings her to the next screen:
![4 4 - project details view](https://user-images.githubusercontent.com/1899506/124264291-959feb00-db34-11eb-997c-00fcee295b04.png)

We've added a "files tab" to the project view. This is shown for **the finance user only**. Here they see all the files that have been uploaded to Hypha that are related to the project. Adding a files tab is being handled by issue #2414.

## Necessary changes

**Dashboard**
- [x] dashboard that shows a table of invoices that have been approved by staff but not by finance.
- [x] When the finance user logs in they see their dashboard - by default it shows the invoices that need to be reviewed.
- [x] 'Submitted date' was when the invoice was submitted 
- [ ] 'Invoice Reference Number' is project name and unique invoice number
- [ ] 'Status'
- [ ] When and which PM/Lead approved the invoice
- [ ]  view of "Show all invoices"
- [ ] In 'Show All Invoices', invoices that have been approved by the finance user and the date invoice has been approved for payment.

**Search & Filters**
- [ ] Search box associated with invoice reference number
- [ ] Search project by name
- [ ] Available filters:
- invoices that have been approved (as a status)
- projects accepted for funding but has not yet started (as a status)
- contracting creation phase or contracting (as a status)
- Filter by Fund
- Filter by Lead

**Comment by frjo** [comment]
@sks444 Updated this issue, Finance role no longer need a Dashboard etc.

**Comment by fourthletter** [comment]
Individuals working in our Finance Dept has the "Staff" role in WagTail. This isn't urgent, but maybe "Staff" should be renamed to "Program" or "Team Reviewer"

<img width="623" alt="Screen Shot 2021-06-14 at 4 48 16 PM" src="https://user-images.githubusercontent.com/20019656/121912257-bb558380-cd30-11eb-9f67-877721778747.png">

**Comment by frjo** [comment]
@sks444 Updated this issue again, Finance role do need a Dashboard etc.

**Comment by fourthletter** [comment]
The UI looks amazing on test, this issue is 90% complete pending a few refinements. The search & filter features are  currently NOT available over the dashboard. 

**WagTail Admin**
- [x] create finance user role in WagTail Admin
- [x] assign user to Finance role in WagTail Admin

**Dashboard**
- [x] dashboard that shows a table of invoices that have been approved by staff but not by finance.
- [x] When the finance user logs in they see their dashboard - by default it shows the invoices that need to be reviewed.
- [x] 'Submitted date' was when the invoice was submitted 
- [ ] 'Invoice Reference Number' is project name and unique invoice number
- [ ] 'Status'
- [ ] When and which PM/Lead approved the invoice
- [ ]  view of "Show all invoices"
- [ ] In 'Show All Invoices', invoices that have been approved by the finance user and the date invoice has been approved for payment.

**Search & Filters**
- [ ] Search box associated with invoice reference number
- [ ] Search project by name
- [ ] Available filters:
- invoices that have been approved (as a status)
- projects accepted for funding but has not yet started (as a status)
- contracting creation phase or contracting (as a status)
- Filter by Fund
- Filter by Lead

**Project Page**
- [x] finance user needs to see a specific project, she clicks on the project name, e.g. Maya Summit, which brings her to the next screen
- [x] project page, the invoices and reports, uploaded files (PDF invoices etc.) and the project communication tab.
