### ISSUE TITLE
Add files tab to project view

### ISSUE THREAD

**Issue by ei8fdb** [HyphaApp/hypha#2414]
The OTF finance user wants to use Hypha as the main place to **view** (this doesn't mean store) files related to an individual project. 

## Sub-issues
- https://github.com/HyphaApp/hypha/issues/2634

## UI Demo

https://user-images.githubusercontent.com/1899506/121543330-1d4c7b00-ca09-11eb-8266-8e5975ca8f5f.mp4

## UI Designs

In the files tab view they see all the files that have been uploaded to Hypha that are related to the project:
![4e - files view - all files](https://user-images.githubusercontent.com/1899506/121170748-eb46e780-c855-11eb-9800-b7517d6cb14f.png)

The file category dropdown options come from the different file upload fields in Hypha - 

The applicant uploads:
- their W8 or W9 file
- invoice files (stored on IntAcct, requested via API)

The internal fund users uploads:
- upload contracts

@frjo mentioned the file category can be stored as metadata, so we can provide this file category filter.

### Search for file
They can search for files with particular words in the file name, e.g. search for files with "invoice" in the name:
![4f - files view - search for invoices](https://user-images.githubusercontent.com/1899506/121201526-e2194300-c874-11eb-991d-a3ea4817c05c.png)

### Filter by file category

![4g - files view - filter for contracts](https://user-images.githubusercontent.com/1899506/121201602-efcec880-c874-11eb-89f1-95505ffbd13f.png)

#### Stored on Hypha
- contract
- W8/W9 file, OFAC and SAM check results (compliance related) 

#### Finance system
(OTF - IntAcct)
- invoices (initially stored on Hypha, until they are approved, then they are moved to IntAcct)

**Comment by fourthletter** [comment]
Program Managers/Program Team/Staff role would need to view the same tab of documents. Program needs this view to track the progress or trajectory of payments associated with a contract. This information enables program managers to project whether a contract needs an amendment in the future, is on track to completion, follow-up with contractors if an invoice is missing from the files, etc.

Partner role may also need the same file tab because these are the documents they've submitted.

**Comment by frjo** [comment]
I think we will store all files in Hypha, AWS S3. If OTF want to we can add a copy of the PDF when invoice are created in IntAcct.

**Comment by Erioldoesdesign** [comment]
Would be good to get a rough estimate from dev and design on how much effort the files tab would be to do a minimum amount of days/hrs would be good for now so that we can better understand the scope of this files tab feature and how feasible it is to be able to be done in 2021's SOW or move to 2022 SOW.

From my understanding this isn't 'blocking' the ability for users to find the needed files, it's a pain to go back into the applicant section to find CV and budget docs but not impossible so I would classify this as 'a very nice to have' and 'improvement issue' for finance & compliance work.

**Comment by ei8fdb** [comment]
> Would be good to get a rough estimate from dev and design on how much effort the files tab would be to do a minimum amount of days/hrs would be good for now so that we can better understand the scope of this files tab feature and how feasible it is to be able to be done in 2021's SOW or move to 2022 SOW.

For design - I think this would be a "medium" t-shirt size -
- the design work to extend this to compliance and contracting is relatively easy
- the reseach work to understand whats needed for compliance and contracting needs to be done
- then there's other questions I've not thought about like 1) how do files get uploaded, 2) what happens with versions (delete old versions, upload new and show old versions), and probably others 
- then we'd need to test it with users

**Comment by Erioldoesdesign** [comment]
Pinging @frjo I know your busy on active dev work for finance but when you get a chance a quick 'sizing' would be good on this one :)

**Comment by ei8fdb** [comment]
@frjo @sks444 @Erioldoesdesign @fourthletter I've created #2634 to discuss the files tab.

**Comment by fourthletter** [comment]
@ei8fdb please move this issue to https://github.com/OpenTechFund/apply-app/issues -- thank you!

**Comment by ei8fdb** [comment]
Same as your other request, I've looked thru the issue management UI but I can't see how to move this. 

You'll have to do it @fourthletter

**Comment by fourthletter** [comment]
I moved it to https://github.com/OpenTechFund/apply-app/issues/25
