### ISSUE TITLE
Remit Status

### ISSUE THREAD

**Issue by saoun** [HyphaApp/hypha#2441]
Not sure if this is intended or a bug, but this is the screen that shows everytime an application needs to be screened. What is the difference between these options? 

![Screenshot 2021-06-24 11 27 30 AM](https://user-images.githubusercontent.com/11432628/123333047-44c63c00-d50f-11eb-914a-26209ef83688.png)

**Comment by frjo** [comment]
I will look at this.

**Comment by fourthletter** [comment]
I created this bug. I didn't know the difference between Y/N and Default Y/N. I'm currently using **In Remit** because I changed it from "Accept." I didn't want to delete **In Remit (IR)**. If it's any consolation, I feel guilty every time I do screening.

@saoun I removed the second "in remit", we only have one now. I'm closing this issue.

<img width="1087" alt="Screen Shot 2021-06-28 at 8 06 46 AM" src="https://user-images.githubusercontent.com/20019656/123588327-e25b8d00-d7e7-11eb-8bf6-916ab5c065de.png">

<img width="1096" alt="Screen Shot 2021-06-28 at 8 08 29 AM" src="https://user-images.githubusercontent.com/20019656/123588420-09b25a00-d7e8-11eb-8c78-9a62f510483f.png">
