### ISSUE TITLE
How to handle translation files in PR the best way?

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#2515]
We now have `hypha/locale/en/LC_MESSAGES/django.po` plus `hypha/locale/django.pot`. They need to be generated with this command.

`python manage.py makemessages --locale en --ignore venv --keep-pot`

When we get around to fixing translation of all string in the templates as well many PR:s will affect the translation files. This will lead to a lot of merge conflicts.

How do we best handle this?

One idea I have is that we ignore the translation files in normal PR:s and then update them in separate PRs on a regular basis. Maybe I do it before each release as needed?

**Comment by sandeepsajan0** [comment]
@frjo  Instead to do it before each release, we can do it weekly like on friday? Because releases will lead to many changes in translations files, so mistakes chances are also high. 
I am searching to find something better, I'll update here as I'll find something good.

**Comment by sandeepsajan0** [comment]
@frjo  I am reopening it, because we got something to share here and it needs your view as well.
We researched about it, and here are our findings:
1. We can manage the translations with a weekly/regular PR 

    -  We can make this PR directly to main branch same like the other PRs.
    - Or, we can also use a separate branch just to manage the translation, it will help us to keep track on translation commits as well.

2. If these files are only getting generated by a command and we don't need to change it manually. then we may also create it in CI-CD pipeline silently. I am just not sure if there can be a case that we may need to change these files manually. It seems a better option to us but just manually editing case can create issues.

Let us know, what are your views on these points.

**Comment by frjo** [comment]
@sandeepsajan0 The files on always generated bu the Django `makemessages` cli command. There is never any need to manually edit them.

Let's go with weekly/regular PR that I handle for this. We can return to this if issues arise from this workflow.

**Comment by sandeepsajan0** [comment]
okay @frjo . Then, I am closing this issue.
