### ISSUE TITLE
A CSV file got uploaded even if it's not an allowed file type

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#2570]
This was on a submission upload field.

**Comment by sandeepsajan0** [comment]
@frjo  It is happening because of `.txt`, I searched a bit found [this](https://stackoverflow.com/questions/48000690/restricting-html-file-input-to-accept-only-txt-and-not-csv-in-chrome) and [this](https://bugs.chromium.org/p/chromium/issues/detail?id=646941). Looks like there is an issue with Chrome and `.txt` extension, it is treating multiple other extension like `.csv`, `.docs` as `.txt` extension.  I checked it by removing `.txt` then it works fine. 
I am still looking for the other options that we can use to handle this.

**Comment by frjo** [comment]
@sandeepsajan0 Excellent that you found the cause of this!

**Comment by frjo** [comment]
@sandeepsajan0 And progress in fixing this issue?

**Comment by sandeepsajan0** [comment]
@frjo I tried to search for it but couldn't find any good thing yet. I think we might need to override some js for that. I'll try with that.

**Comment by fourthletter** [comment]
relates to #2462

**Comment by sandeepsajan0** [comment]
I went through the many issues and docs but couldn't find a good fix for this one. As we know, this is happening only with Chrome or Chromium and working fine in safari and other browsers. For the safe side, we already have a placeholder that mentions all accepted file types, so I think it is okay for now until we get something solid or get this issue fixed by Chromium. 

What do you think @frjo ?

**Comment by frjo** [comment]
Thanks for looking in to this issue. I agree that we can live with this issue. Closing this for now.
