### ISSUE TITLE
Setting page privacy sends login in users to _util/login

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#2599]
When setting privacy to a wagtail page on the public part of Hypha

![Skärmavbild 2021-10-19 kl  12 56 51](https://user-images.githubusercontent.com/191392/137896321-c225dee8-cfeb-4cef-9fe6-d54aa7ab2618.png)

Even logged in users get redirected to this login screen.

![Skärmavbild 2021-10-19 kl  12 58 46](https://user-images.githubusercontent.com/191392/137896490-5409868d-049d-4959-9a6b-ae5fe7689e22.png)

**Comment by frjo** [comment]
@Parbhat I guess this is a bug in Hypha? Know we have done stuff to login on the public side.

**Comment by Parbhat** [comment]
@frjo It is not a bug. Wagtail by default has a different login [view](https://github.com/wagtail/wagtail/blob/571b9e1918861bcbe64a9005a4dc65f3a1fe7a15/wagtail/core/urls.py#L31) for the private pages. From [docs](https://docs.wagtail.io/en/stable/advanced_topics/privacy.html?highlight=WAGTAIL_FRONTEND_LOGIN_TEMPLATE#setting-up-a-login-page), it seems like we should set the settings WAGTAIL_FRONTEND_LOGIN_TEMPLATE

>To integrate Wagtail into a Django site with an existing login mechanism, setting WAGTAIL_FRONTEND_LOGIN_URL = LOGIN_URL will usually be sufficient. - [docs](https://docs.wagtail.io/en/stable/advanced_topics/privacy.html?highlight=WAGTAIL_FRONTEND_LOGIN_TEMPLATE#setting-up-a-login-page)

**Comment by Erioldoesdesign** [comment]
Can I add this to the [OTF's Ye Olde Bug & Refinement Shoppe](https://github.com/HyphaApp/hypha/projects/14) board?

**Comment by frjo** [comment]
Yes

**Comment by sandeepsajan0** [comment]
**Findings**: I tried to add WAGTAIL_FRONTEND_LOGIN_URL but it didn't worked out because https://test.hypha.app/login/ is not working, login is only working for https://test-apply.hypha.app/login/.  I tried many ways to redirect to the working login url but at the end I got looping issue in between login url and target page because of different domain and user is not authenticated for public pages.
Then I worked to make [public login page](https://test.hypha.app/login/ ) working, and there is only issue that [forgot password or password reset url](https://github.com/HyphaApp/hypha/blob/main/hypha/apply/users/templates/users/login.html#L38) is not public. I tried by removing only this line and it worked, and private pages also worked as expected.

So, Should we rearrange the urls to make password_reset public or We don't need Forgot password on public page?

**Comment by frjo** [comment]
I think skipping password reset on public login is ok. Normally we direct all logins to the apply login.
