### ISSUE TITLE
[Files tab spike]: what does the files tab need to do for users

### ISSUE THREAD

**Issue by ei8fdb** [HyphaApp/hypha#2634]
## Additional context
This is a sub-issue of the epic #2414.

## What happens now?
Staff need to use different tools to manage the full application process: from application to review to contracting to invoicing and finally finishing a project. Applications are stored in the Hypha webapp, files related to applications are stored in a cloud storage tool. Staff need to download files from Hypha, then upload them to the cloud storage, vice-versa. This means a lot of extra manual admin work for the staff.

The idea of moving the files from the cloud storage tool to Hypha was raised during the finance workflow.

This would mean that all files related to the application (including *but not limited to*: budgets, contracts, invoices, receipts, supporting documents like CVs/bios, results of compliance checks, etc) could be managed/referenced/maybe viewed in Hypha instead of the constant downloading/uploading. 

We are suggesting the Files tab as a way to:
- reduce (and ideally remove) the repeated and required uploading and downloading of files from Hypha to cloud storage, and vice-versa
- centralise the storage of files associated with a project from application to invoicing and beyond in **one tool**
- provide a way for different user roles with the right permissions to view files they should be able to access 

## What is the minimum the files should tab do?
To start of discussions, the following list is an unvalidated list of the minimum functionality I think is needed. This list would need to be validated with PM, finance and legal users.

- make the files tab visible for the pm, finance and legal users
- have permissions based access to files
~- should allow finance and legal users upload a file~
- it should display files that have been uploaded:
  - by applicants during the concept note stage
  - by applicants during the full proposal stage - e.g. cvs/bios/budgets/
  - by applicants as part of the vendor set-up process - e.g. w8/w9 forms
  - by applicants during the project in progress phase - i.e. invoice pdfs
  - contract files
  - all the above files in a simple list
- the simple list should:
  - include the date the file was uploaded
  - the username of the user that uploaded it 
  - allow pm/finance/legal users search for a file by name/part of name
  - allow users organise them by date/reverse date

## To be added later
Eventually the following should be added:
- file activity should be added to the activity tab
- be visible for the applicants
- it should allow users filter the files by file category 
- it should display files that have been uploaded by applicants during the project in progress phase - i.e. receipts, and other files
- and others we don't yet know about

@fourthletter: Focusing on whats in the "## What is the minimum the files should tab do?" list - is there anything that you **know is needed but not** listed there? Is there anything I've listed there that you **know is not** needed? Please focus on the *minimum* that users need.

@frjo @sks444 - I'd like to hear your thoughts on how much work this is. How much effort is it to add this functionality?

**Comment by frjo** [comment]
I want to restate my opinion that the files tab has nothing to do with uploading files. It is a view where staff etc. can view all uploaded files that belong to a project.

If we do not already allow uploads of all needed files in to Hypha that is a separate issue. Is there files that should be in Hypha that are not already possible to upload?

**Comment by frjo** [comment]
Who is it that needs this files tab? For what tasks?

The best I think is if we can show every user group everything they need on each step in the workflows.

The PAF should show everything needed to approve a project, an invoice should show everything needed to approv it etc.

**Comment by ei8fdb** [comment]
> If we do not already allow uploads of all needed files in to Hypha that is a separate issue.

You're right - allow uploads of all needed files in to Hypha is a separate issue.

>  Is there files that should be in Hypha that are not already possible to upload?

For the moment I _think_ it is the finance users and the compliance users being able to add the compliance check results. Instead of uploading the compliance check results to the cloud storage - like now: 

![image](https://user-images.githubusercontent.com/1899506/142207589-7c71d95c-d608-4b4b-b46c-faa94ed28dcc.png)


they could upload it to Hypha.

**Comment by frjo** [comment]
We already have "Supporting documents" uploads. Adding a upload field for that instead of the textbox above would allow them to upload the files directly to Hypha.

**Comment by fourthletter** [comment]
> The best I think is if we can show every user group everything they need on each step in the workflows. 

@frjo My rudimentary interpretation of what each group can and should access in the finance/contracting workflow


 **Table 1: Which documents could user groups access?**

User Group | Full Proposal| Vendor Set-up | Project in Contract Phase  | Project in Progress Phase
------------ | ------------- | -------------| -------------| -------------
staff  | Yes | Yes  | PAF, W8, W9, Contract | Invoices, receipts| 
finance 1  | No |  Yes | PAF, W8, W9, SAM, OFAC |  Invoices, receipts| 
finance 2  | No |  Yes | PAF, W8, W9, SAM, OFAC | Invoices, receipts | 
contracting | No |  No | PAF, W8, W9, SAM, OFAC | No | 
approver| No |  No | Contract | No| No | 
applicant| Yes |  Yes | Contract |Invoices, receipts | 

 >  What is in the "## What is the minimum the files should tab do?" list - is there anything that you know is needed but not listed there? Is there anything I've listed there that you know is not needed? Please focus on the minimum that users need.            
             
@ei8fdb I suggest the file tab should have documents that will continually proliferate over the full lifecycle of a funded project/contract. However, I could wait for more discovery and user research to confirm my reasoning.

 **Table 2: What is the minimum the files should tab do?**

Doc Type | Full Proposal| Vendor Set-up | Project in Contract Phase  | Project in Progress Phase
------------ | ------------- | -------------| -------------| -------------
 | invoice|  |  |  | ongoing | 
 | receipts |  |  |  |ongoing | 


> We already have "Supporting documents" uploads. Adding an upload field for that instead of the textbox above would allow them to upload the files directly to Hypha.

I agree with frjo that we should use other means/vehicles for storing data, and that the files tab is not our only option.

A majority of documents listed below only need to be completed once during a full lifecycle of a funded project/contract. The user interface for this feature needs work since the placement of documents should be consistent from project to project.

**Table 3: Which documents are needed for finance/compliance?**

Doc Type | Full Proposal| Vendor Set-up | Project in Contract Phase  | Project in Progress Phase
------------ | ------------- | -------------| -------------| -------------
csv/resume | 1 | 
bios | 1| 
budgets |1 | 
w8/w9 forms |  |  1 |  | | 
 | contract |  |  |  1| | 
contract amendments |  |  |  1| | 
 |SAM|  |  | 1 | need to check the same version every time a payment is processed| 
 | OFAC |  |  | 1 |need to check the same version every time a payment is processed | 
 | SOW|  |  | 1 | | 
 | Sole Source |  |  | 1 | | 
 | PAF |  |  | 1 | | 
 | Bank details|  | 1 | 1| | 

Grab the 🍿 , I have a gif

![Kapture supporting document upload](https://user-images.githubusercontent.com/20019656/142938829-f02d5d26-d680-431c-8027-19378d846066.gif)

**Comment by Erioldoesdesign** [comment]
Related we.hypha post here: https://we.hypha.app/t/what-does-the-files-tab-need-to-do-for-users/237

Collecting x-adopter feedback is scheduled for Jan 2022 Adopters call: https://we.hypha.app/t/monthly-adopters-meeting-2022-january-26th/228
