### ISSUE TITLE
Allow control over who reviewers can communicate with

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#2658]
This refers the the visibility settings in the communication tab on submissions. Right now reviews can select "Reviewers" and "All".

**Comment by Erioldoesdesign** [comment]
Does this need design from a UX pov?

**Comment by sandeepsajan0** [comment]
@frjo Currently, we are using the same visibility options/permissions for a user for all activities(comments and actions) irrespective of its types from [here](https://github.com/HyphaApp/hypha/blob/main/hypha/apply/activity/models.py#L130).  Do we need to separate the visibility permissions for comments and activity in this case?

**Comment by frjo** [comment]
@sandeepsajan0 Hold on this one, we need to discuss what is really needed by the users first.

**Comment by Erioldoesdesign** [comment]
Looks like this needs some brief user survey/interviews across the program management of an application to see who need to see communications tab at what points in a workflow process.

Example hypothesis: Program Manager lead might want finance team members to see communications related to budget/invoices/finance information but not 'all' staff to see the communication tab in budget/invoice/finance information.

Should probably have a design research issue created to understand this user need :)

**Comment by chriszs** [comment]
ARDC asked us to remove ability for applicants to see comments in large part because they didn't want applicants to see comments from reviewers left visible to them by mistake. What we've done is to remove the comments tab for applicants and changed the permissions so applicants aren't included in "All" then renamed that to "everyone but applicants." I also renamed most other visibility categories to add "and staff," as in "Reviewers and staff," because my understanding is the way it's set up staff can see most categories regardless.

This is the result:
<img width="260" alt="Screen_Shot_2022-02-18_at_1 58 10_PM" src="https://user-images.githubusercontent.com/1103467/155380615-2bb96760-e37c-4b50-bc40-5492be27a564.png">

**Comment by emlini** [comment]
In looking at the options in sandbox today, I was wondering if we might want to have checkboxes for each role, or a dropdown menu that populates a separate "addressee" box rather than the radio buttons.  That allows more control over which specific user types see communications relevant to them. The second option (dropdown menu populating an "addressee" box makes it more email-like (which I HOPE folks are used to).

Downside: 
Both of these options still leave open the possibility that Applicants are accidentally selected to receive communications not meant for them.

Possible solution: we could also try building in a warning popup that activates any time "Applicants" is selected to ask "DID YOU MEAN TO SEND THIS MESSAGE TO THE APPLICANT/FUNDEE?

**Comment by emlini** [comment]
> This is the result: <img alt="Screen_Shot_2022-02-18_at_1 58 10_PM" width="260" src="https://user-images.githubusercontent.com/1103467/155380615-2bb96760-e37c-4b50-bc40-5492be27a564.png">

@chriszs what does "Partners" mean to ARDC?  In the [Hypha Roles doc page](https://github.com/HyphaApp/hypha-docs/blob/c0f376acb2a9ed8ed84eb332a8d3c6be2ee72aa6/staff/hypha_roles.md), I have defined it as a kind of co-applicant (based on communication with dev and other users), but from your comment it doesn't sound like this is how ARDC is using the term/role. Can you clarify who "Partners" refers to for ARDC and what kinds of permissions that role has in their implementation?

**Comment by chriszs** [comment]
@emlini It's a good question, and one they'd have to answer. They're not in production just yet, we hope they will be after this week. If it means that to them, I might have to go remove it from that role as well.

**Comment by Erioldoesdesign** [comment]
@emlini Partners might mean (in my knowledge) either: 

1. The fund applicant has 'partners' that they work with on the fund they have and so partners are included in some invoices. e.g. ARDC funds 'Project Megacool'. 'Project Megacool' hires Fredrik to do some development work and Simply Secure to do some design work. Fredrik and Simply Secure then become 'partner contractors' on that fund.
2. Partners can sometimes mean 'The board' or 'The community review panel' etc. so not people 'employed' by a funder org but who support an application.
3. both

I think the most common one is number 2.

Re. the UI improvements - I agree that checkboxes of each role type would be good but could also become tricky if you have many 'groups':
<img width="609" alt="Screenshot 2022-02-28 at 12 17 44" src="https://user-images.githubusercontent.com/11681324/155982262-3718910d-344f-430f-9cd1-c99daab6f241.png">

It could be nested parent/child checkboxes so:

- [ ] Staff
  - [ ] Finance
  - [ ] Compliance
  - [ ] Approver
  - [ ] etc.
- [ ] Applicant
   - [ ] Applicant primary
   - [ ] Applicant secondary
   - [ ] Applicant
- [ ] Partners
    - [ ] Community reviews
    - [ ] The board

I'm also very pro a 'did you want communications to be visible to applicants?' warning message before 'saving'

**Comment by fourthletter** [comment]
Hi @sandeepsajan0 these changes make sense:

but we're keeping 'Applicant(s)' because OTF's applicants need to access the comments

<img width="260" alt="Screen_Shot_2022-02-18_at_1 58 10_PM" src="https://user-images.githubusercontent.com/1103467/155380615-2bb96760-e37c-4b50-bc40-5492be27a564.png">

**Comment by fourthletter** [comment]
> Partners might mean (in my knowledge) either:
> 1. The fund applicant has 'partners' that they work with on the fund they have and so partners are included in some invoices. e.g. ARDC funds 'Project Megacool'. 'Project Megacool' hires Fredrik to do some development work and Simply Secure to do some design work. Fredrik and Simply Secure then become 'partner contractors' on that fund.
> 2. Partners can sometimes mean 'The board' or 'The community review panel' etc. so not people 'employed' by a funder org but who support an application.
> 3. both

'Partner' could revise an application, but cannot submit reviews so they are rarely board members, external reviewers, or advisory committee members. 

We have a fellowship program that connects fellows with host organizations (ie university), host organizations could become a 'Partner' and access the application. If an applicant wants to have another individual in their organization access/edit their application, this individual could be designated as a 'Partner.'

**Comment by fourthletter** [comment]
On June 6 FJ + DL discussed creating a new setting for staff to manage and control comments that are visible to reviewers and applicants. This is a more complex issue in scope than revising the visibility user interface https://github.com/HyphaApp/hypha/issues/2873

**Comment by fourthletter** [comment]
## User stories

1. As a user I need better instructions or guidance on the comment's section visibility settings. 
2. The default setting for 'Partner' is 'Partner' -- users often submit a comment to themselves and can't be view by anyone else

## Current 
![image](https://user-images.githubusercontent.com/20019656/187277724-a6ee07be-8531-4a6a-8262-85fd112a4581.png)

## Proposed Solution
OTF is keeping 'Applicant(s)' and ALL because OTF's applicants need to access the comments

<img width="260" alt="Screen_Shot_2022-02-18_at_1 58 10_PM" src="https://user-images.githubusercontent.com/1103467/155380615-2bb96760-e37c-4b50-bc40-5492be27a564.png">
