### ISSUE TITLE
[META/EPIC] Discovery with Adopters re. expectations of Hypha.app / 'headless' Hypha

### ISSUE THREAD

**Issue by Erioldoesdesign** [HyphaApp/hypha#2707]
From a discussion at Feb 1st maintainers call

Hypha.app is a ‘headless tool’ that powers the application. Discovery with Adopters re. expectations of Hypha.app

Skin templates for public website e.g. Wagtail front-facing website. Other Adopters don’t use this theme because it doesn’t match what they want from their website. Adopters want to use Hypha for both ‘apply backend’ only or ‘front website + apply backend’ how is this supported going forward?

A design research piece with both current adopters + potential funders that could be adopters.

**Comment by fourthletter** [comment]
### Ideation Call February 2022
notes regarding this issue https://we.hypha.app/t/monthly-ideation-meeting-2022-february-22nd/254

Bernards 3 options:

Hypha has a management UI for managing fund stuff & Hypha has a application UI to display the fund stuff that looks the same as the funder website but is not the same

Hypha has a management UI to create funds & manage applications & organization uses ‘website UI’ (that can recieve an API endpoint from Hypha) to display the application part that applicants would actually access and fill out

Info requested from Hypha and displayed on organisations website. ‘See who we fund’ rendered in wordpress but info pulled from Hypha e.g. Project name, description, fund name, advisory council.

^^^^ All of the above could be done within an API via end points and ‘choosable’.

These are all potential use cases. What is the dev process and dev resources to make the mvp of this idea?

Bernard’s research: Most Adopters are using Wordpress CMS Hosted


### Adopter's Call February 23, 2022
Topic was raised again, basic notes here: https://we.hypha.app/t/monthly-adopters-meeting-2022-february-23rd/244
What would “Headless” Hypha look like?
Option 1: in WagTail where create funds, rounds, forms, etc. There will be a Hypha’s application UI for the user to run the fund there. This would be seprate from the Funder’s website. Technically Hypha already supports this. Example: DFF apply website (separate from their main page, requires a lot of work to make Hypha apply page match org website in terms of theme, etc.–right now this isn’t very easy in Hypha)
Option 2: Hypha’s Fund management UI. Funder’s website is used to display the application forms. Application forms are embedded on Funder’s website. Instead of being brought to another Funder’s address, applicants would apply to a form “embedded” on the Funder’s website. There are technial questions about how to best embedd application forms on the website like a google form. Or a plug-in that doesn’t look like an embed
Option 3: Funder’s website and the apply site. What information is pulled from Hypha and displayed on the website? For example, the external reviewers could be pulled from Hypha and displayed on the website.

**Comment by fourthletter** [comment]
Related to #2506

**Comment by frjo** [comment]
I think the talk about Headless Hypha is no longer relevant. From my experience new Hypha users just want a system that works as good as possible out of the box. No one have expressed a wish to build a custom front end them self.

If specific API endpoints need to be added or extended we can deal with that in separate issues.

I would close this one.

**Comment by fourthletter** [comment]
> I think the talk about Headless Hypha is no longer relevant. From my experience new Hypha users just want a system that works as good as possible out of the box. No one have expressed a wish to build a custom front end them self.
> 
> If specific API endpoints need to be added or extended we can deal with that in separate issues.
> 
> I would close this one.

Thanks for your input. I'll close this issue.
