### ISSUE TITLE
Validation of Requested amount on submissions and value on Projects are not the same creating issue

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#2743]
Entering a large value on a submission will result in an error when creating a project from that submission.

```
psycopg2.errors.NumericValueOutOfRange: numeric field overflow
DETAIL:  A field with precision 10, scale 2 must round to an absolute value less than 10^8.
```

https://github.com/HyphaApp/hypha/blob/7418f05fa0a5bea4504beaac761b33988eea622a/hypha/apply/projects/models/project.py#L138-L143

https://github.com/HyphaApp/hypha/blob/7418f05fa0a5bea4504beaac761b33988eea622a/hypha/apply/funds/blocks.py#L36-L45

**Comment by sandeepsajan0** [comment]
@frjo Do we need to have the `max_digits` validation there in projects. I think it would be better not to use that because if we will try to add the same validation in application submission then we may need to update the existing data as well(via custom migrations) and I also couldn't see its need. So, if that validation is not necessary we can remove it and it all will be fine then. 
What do you suggest @frjo?
