### ISSUE TITLE
When submitting an application as a logged in user, the email and name is silently overridden with the user's

### ISSUE THREAD

**Issue by chriszs** [HyphaApp/hypha#2758]
**Describe the bug**

As a logged in user, when you submit an application the name and email are silently replaced with the logged in user's.

**To Reproduce**

1. Log in to Hypha
2. Go to apply for funding
3. Fill in application details, including a name and email which are not in your account
4. View the application

**Expected behavior**

The name and email supplied are used.

**Priority**

- High (keeping you from completing day-to-day tasks)

**Affected roles**

- Staff
- Applicants

**Additional context**

This was an issue that surfaced in a ARDC review, we made a quick fix which was to disable the silent override of the name and email. For reasons that will become apparent in related issues, I now believe the better solution would have been to show the logged in user name and email in the submission form with an edit and/or logout link, e.g. the below:

<img width="445" alt="Screen Shot 2022-03-01 at 10 15 22 AM" src="https://user-images.githubusercontent.com/1103467/156195372-cd3f0142-8c49-4cbb-a482-4b772783a5fb.png">

**Comment by frjo** [comment]
The bad part is not communicating it clearly to the user.

We should prefill the values and disable the field or something like that.

If you are logged in to an account the submission will, and should, belong to that account and have the account e-mail used for notifications etc.

**Comment by chriszs** [comment]
Right! I agree pre-filling is the way to go.

**Comment by Erioldoesdesign** [comment]
> If you are logged in to an account the submission will, and should, belong to that account and have the account e-mail used for notifications etc.

Agree with this! as a user of google/other services pre-fill for forms the static text and edit button is one more click away from me filling out this form. 

Disabling the field after pre-filling email sounds good for the user case where the user did mean to associate the new application with the existing email but I think I'll open up an issue or make a note of a use case where you might want to send a new application under a new/different email. Maybe a user changes orgs? changes their email name because of deedpoll/marriage/name change? (i suppose you can change this in user settings? but still worth capturing somewhere this potential tricky stuation.

**Comment by frjo** [comment]
@Erioldoesdesign If you do not want your application to be associated with an account you should not be logged in with that account.

**Comment by chriszs** [comment]
I think the existing fix works well. The two things I'd change are 1) this probably shouldn't be the case for editing an existing application as an admin, and 2) adding a logout or edit profile link in case the user wants to supply different values. Both out of scope for this ticket.
