### ISSUE TITLE
[Meta] Revise error messages

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#2771]
Users receive error messages within Hypha, but the reason for the error is not always clear. We could try our best to reproduce the errors, but it would be helpful to decide next steps for redrafting error messages.

### User did not include required fields in application form

<img width="1232" alt="Screen Shot 2022-02-24 at 8 30 04 PM" src="https://user-images.githubusercontent.com/20019656/157401779-237ab020-a9de-4120-8b59-7f8a42e9aa31.png">

### User sent a batch action determination message

![Screenshot 2021-11-10 9 23 45 AM (1)](https://user-images.githubusercontent.com/20019656/157401822-c9afa6c2-1c75-437d-8898-63b5f2fc47af.png)

### User sent one determination message

<img width="820" alt="Screen Shot 2022-03-09 at 9 26 21 AM" src="https://user-images.githubusercontent.com/20019656/157401982-b48528a2-59e4-4dfc-b5ce-060114598c9e.png">

**Comment by emlini** [comment]
### **Describe the situation:**
I encountered this same issue (unclear error message) when creating a sample Application form in Wagtail on [https://sandbox-apply.opentech.fund](https://sandbox-apply.opentech.fund).  

Attempted to save the form after having added several fields, edited field options, and reordered fields.  Received the error message "The application form could not be saved due to errors"

Form page reloaded and automatically maximized all fields (I had minimized them for ease of ordering/organization).  It was not clear where the error was, and because I had added at least one instance of every possible field in the form, there was *a lot* to review, and I attempted to re-save multiple times guessing at what needed to be fixed.  (I finally discovered that the error was that I had not filled in the "Choice" I created in a Radio Button field).

Priority level: This was frustrating, and took additional time I wished I hadn't needed to spend figuring out where my error was.  I did eventually figure it out, but there was despair.

### **Requested solution:**
1) Somehow indicating which field(s) the error resides in, either with:
 -  red highlighting of the field(s) (a) when one clicks off of a newly-created field without having filled in all required information, or (b) when the page reloads after attempted save, or
 - listing the field(s) that caused in the error message

@ei8fdb and UIX team, I would welcome other thoughts on how this clarification might be implemented.

I can't tell if @sandeepsajan0's recent commits (those linked in this issue thread) do this in either of the ways I suggested (or in some other way).  If so, I would love a ping when the sandbox instance is updated so I can test that out.

**Comment by sandeepsajan0** [comment]
@emlini Thanks for reporting this error message issue. I understand it is frustrating, something similar happened with me as well. 
Actually, "The application form could not be saved due to errors" this message is a wagtail inbuilt message for any kind of error in the form. And I am currently working to override this message with custom messages for every possible condition.
For now(in my recent commits above), I have added the custom messages for required blocks and duplicate blocks only. I'll continue my work on the error msgs as much as I can cover. You helped me by reporting it here, I'll try to add a custom message for this condition as well.

**Comment by sandeepsajan0** [comment]
Another error report: If label(required, field_label) is empty for any block, it is not showing any error or message and also not saving the form. 
<img width="1104" alt="image" src="https://user-images.githubusercontent.com/23638629/160282793-16f5fda0-75a7-4e16-b7d2-13c5c3d76380.png">
