### ISSUE TITLE
Determination Message Template

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#2809]
## User Story

When I send a determination for approved/dissmissed/need more info I would like to have prepopulated text on determination forms. When creating a Fund/Lab these templates would be available to me in the WagTail Admin. Related to #2440 

## Proposed Solution

Set the templates for approved/dissmissed/need more info on each fund

![image](https://user-images.githubusercontent.com/20019656/163360466-0f98c019-a11f-404b-a5ba-4701deca505b.png)

When creating a Fund, I am unable to select determination templates I need

![image](https://user-images.githubusercontent.com/20019656/163361037-13cc6404-0df1-42df-a3d9-2844f503d0b1.png)

related https://github.com/HyphaApp/hypha/issues/2042

## Good to have

Staff can upload attachments to a determination

---
## Internal Approval Process
- [ ] @OpenTechFund/design to add designs to issue
- [ ] @OpenTechFund/devs to review designs for implementation
- [ ] Di to help organise testing/feedback session with OTF users
- [ ] @OpenTechFund/design do testing/feedback session with OTF users
- [ ] OTF to sign-off
- [ ] @OpenTechFund/design to make sure most up to date designs designs are attached to issue

**Comment by sks444** [comment]
Determination messages are [implemented as wagtail setting](https://test-apply.hypha.app/admin/settings/determinations/determinationmessagesettings/2/), based on the outcomes we can set-up three different messages for various submission workflows.

This means we need to populate the message box when outcome is selected while adding determination. 

---

In the standup we discussed creating as many message templates and then having an option to select one while adding determination. And then populate message box based on the selected template.

---

> When creating a Fund, I am unable to select determination templates I need

In the issue description @di mentioned, we need a way to select determination templates while creating funds. 

@frjo, these are three different implementations and the first one looks more promising to me..what do you think?

**Comment by frjo** [comment]
@sks444 @fourthletter We need to pick one of the options.

1. Set the templates for approved/dissmissed/need more info on each fund
2. Set the templates for "approved/dissmissed/need more info for" each workflow type (This is how the feature used to be implemented, see https://test-apply.hypha.app/admin/settings/determinations/determinationmessagesettings/)
3. Add as many templates as needed and then on each individual determination pick the one to use.

For option 1 and 2 the text will be added to the messaging textarea when a determination is picked from the popup, i.e. "approved/dissmissed/need more info".

For option 3 the staff user will just pick the template manually from a separate popup. This was the option I mention in the meeting today.

@fourthletter What option do OTF pick?

**Comment by fourthletter** [comment]
@sks444 let's go with the first option that looks most promising to you. 

Users no longer require unlimited templates, they prefer to select from a narrow list of templates and make adjustments/edits when necessary.

**Comment by fourthletter** [comment]
On May 10 standup we discussed replacing the old hard code forms with new streamfield forms.

**Comment by sandeepsajan0** [comment]
@fourthletter  @frjo @sks444  Currently, the old hard code forms are getting used as backup forms.
I noticed in my local that sometimes the determination form is attached to funds but it is not attached to its respective round and in that case, our old hard code form is getting rendered.

So, I think first we should remove the usage of old hard code forms and force/guide users to add a streamfield form to round via fund then we can remove the old forms' code as well. 
And I think it should be a separate issue to remove old hard code forms. As determination message template for streamField form is fixed in #2844 and also does not create any issues with old forms.

**Comment by frjo** [comment]
When a new Fund or Lab is set up the determination forms are required so it is not possible to use the old hard coded forms on them. Just as we want.

**Comment by sks444** [comment]
And the round is supposed to copy the determination form from funds.  So it's shouldn't be the case the that a fund has the determination form but round doesn't. @sandeepsajan0 can you check on why this is happening?

**Comment by sandeepsajan0** [comment]
Yes, @frjo and @sks444 you both are right. Actually, It was an issue with my local.

It was an older/existing round using an existing fund that doesn't have a determination form attached at the time of round creation(because we are copying the determination form at the time of round creation only). And maybe later, I edited the fund and attached the determination form to it but didn't change/update the round. That's why the determination form is attached to the fund but not to the round. It is a kind of edge case.

For the new funds or new rounds, it is working just fine.

**Comment by fourthletter** [comment]
On May 12 standup we discussed:

In the Determination Message Settings, there are currently options for two workflows: 1) Request (one stage) and 2) 2-Stage (concept note and proposal). 

The approach we are choosing is to use Request for RequestComm and RequestExt. This would minimize the admin burden for maintaining these templates within WagTail, and streamline pre-populated templates/messages options for program managers. 

![image](https://user-images.githubusercontent.com/20019656/168036180-f2f3b34e-d8aa-4632-a7b1-14696ea7e5e2.png)

**Comment by fourthletter** [comment]
Thank you! Works like a charm 🥇 

![image](https://user-images.githubusercontent.com/20019656/168604524-14894444-3601-4e7a-977c-30d6b6d356fc.png)
