### ISSUE TITLE
Add Regional Categories to Results Page

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#2847]
### Description
A table of regional categories and number of submissions associated with each region

![image](https://user-images.githubusercontent.com/20019656/168598027-9be8df16-9865-4bf4-8baf-882355c4bf01.png)

**Comment by frjo** [comment]
You can filter on categories that you check "FILTER ON DASHBOARD" in Wagtail admin.

But maybe you want a separate table (in the summary section?) that show all the regions listed?

This takes some thinking and some configuration options since it is staff in each organisation that set up whatever categories they want/need. OTF happens to have set up one for regions.

**Comment by fourthletter** [comment]
A separate table (in the summary section?) that shows all the regions listed would be nice. 

However, if "each organisation sets up whatever categories they want/need," it becomes difficult to create tables on a results page solely based on category questions. The results page is not scalable and replicable from organization to organization (or user to user). 

We need data that is commonly required and collected among different organizations, but also flexible enough so that each organization could adjust  what they need to see on the results page. We may change the question asking for regions in the future, making this table on the results page useless. 

The platform is flexible enough for an adopter to choose a category question, meta question, or another method to collect geography data. This impact how results are collected and displayed on the results page.
