### ISSUE TITLE
As a manager, I need a clear summary for all accepted submissions

### ISSUE THREAD

**Issue by danblah** [HyphaApp/hypha#287]

**Comment by fourthletter** [comment]
Closing this issue because a summary of all accepted submissions exists. 

https://test-apply.hypha.app/apply/submissions/result/

<img width="1094" alt="Screen Shot 2021-04-27 at 10 09 33 PM" src="https://user-images.githubusercontent.com/20019656/116306360-412f6680-a7a5-11eb-8e76-13262e2afd01.png">
