### ISSUE TITLE
Enhance Supporting documents upload

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#2921]
## Additional context
This is a sub-issue of #2911  

## User Story
> As a contractor I need to provide my banking, tax information to the funder so they can setup me up in their accounting system.

**What the user needs to do**
In Hypha the contractor needs to submit this information to the **Supporting documents table**:

**What staff needs**

* Editable list of document categories that are needed.
* Mark uploads as approved etc.

![Screenshot 2022-07-11 11 28 16 AM](https://user-images.githubusercontent.com/20019656/178234164-ef3c1683-1509-4a5c-b00d-c5e3ca18fe3d.png)

## Priority
- High (keeping you from completing day-to-day tasks)

## Ideal deadline
October 2022

**Comment by sandeepsajan0** [comment]
> 3. upload completed w8 or w9 form (depending on their US tax status)

@fourthletter Do we want this field just as a checkbox(boolean, just to confirm if it belongs to w87 or w9), or do we need a dropdown to select the form type?

One more point I am thinking about is, Supporting documents are not only for contracts(I guess) so it may look odd to add contracts related fields in there. Don't you think @frjo?

**Comment by frjo** [comment]
@sandeepsajan0 @fourthletter The contract are uploaded in a separate place, not related to Supporting documents.

![Skärmavbild 2022-08-24 kl  10 36 16](https://user-images.githubusercontent.com/191392/186371720-80508949-2d91-48a5-8f95-253371bd0248.png)

**Comment by frjo** [comment]
@fourthletter The w8 and w9 forms in point 3 sounds a good fit for "Supporting documents" in case the vendor setup is not used.

Point 1 and 2 does not sound like documents (e.g. a PDF file) you upload? This sounds exactly like the kind of information we collect in the vendor setup form.

So OTF want to collect this information but not via the vendor form? It is something I do not understand here.

**Comment by sandeepsajan0** [comment]
@frjo  Yes, that's a valid point here. I think instead of moving forward with this issue we should have a discussion regarding this with the @fourthletter.

**Comment by fourthletter** [comment]
On September 20 standup we discussed several approaches for enhancing this feature:

1) As a user, they need to know which documents to upload
2) Know status updates (ie approved)
3) In version 2.0 we will include notifications

![image](https://user-images.githubusercontent.com/20019656/191217600-4954ed68-7df1-4110-a438-12bbe4eda260.png)

**Comment by theskumar** [comment]
Internal data modeling! 
![image](https://user-images.githubusercontent.com/236356/191218809-23c682c1-59bd-46b2-a770-11c6c58cc0af.png)

**Comment by fourthletter** [comment]
On October 11 standup we discussed:

- [ ] The check mark next to the doc upload button
- [ ] pop-up asks for "file name" -- is this necessary?
- [ ] There are two "upload" buttons - consider rename one of button to "submit"
- [ ] date stamp? Or another indicator of a file that is  no longer relevant or version control of documents
- [ ] How could users access documents after the project has been approved? Could contractors upload NEW documents after they have received a contract and started invoicing?

**Comment by sandeepsajan0** [comment]
I did some research into the code regarding the check mark bug and other points and here are the findings:
> The check mark next to the doc upload button

  The mark is checked when the minimum requirement of all document categories are fulfilled. In other words, the number of Uploaded documents per category is equal to or greater than the minimum number of required documents per category, as set in the [wagtail admin](https://test-apply.hypha.app/admin/application_projects/documentcategory/).  
  On the test site, we have document categories but their minimum was set as 0 that's why mark was already checked. I have made the changes there, now it should be unchecked.

>pop-up asks for "file name" -- is this necessary?

it will be removed in PR #2995, and it will use the uploaded document's name.

>There are two "upload" buttons - consider rename one of button to "submit"

It will be renamed in the same PR.

>date stamp? Or another indicator of a file that is no longer relevant or version control of documents

It is not clear yet, although we can show the uploaded date but not sure if it will be enough. I think it is the reason we were talking about the status field. @frjo @theskumar what's your opinion on this one?

>How could users access documents after the project has been approved? Could contractors upload NEW documents after they have received a contract and started invoicing?

Supporting documents are available inside the 'Approval Form' as shown in the below image. No, contractors can't update the project/approval form or the supporting document after the contract approval.

<img width="657" alt="image" src="https://user-images.githubusercontent.com/23638629/195335365-d9168ae7-4020-40c6-81a5-9e078bc4341b.png">

**Comment by fourthletter** [comment]
There's currently a slight glitch. The NEW projects I've created have the same files embedded on them in the supporting document section.

https://test-apply.hypha.app/apply/projects/78/
https://test-apply.hypha.app/apply/projects/79/
https://test-apply.hypha.app/apply/projects/80/

**Comment by frjo** [comment]
I do not see any files uploaded to the three projects you linked to. Only this text

~~~~
Every project should include the following documents:

Bank Details Form (1)
~~~~

**Comment by frjo** [comment]
![Skärmavbild 2022-10-18 kl  21 15 04](https://user-images.githubusercontent.com/191392/196523168-aabbcf36-ea3a-4e59-b6ad-4ca86e7e2bb1.png)

**Comment by fourthletter** [comment]
This look great! 💯
