### ISSUE TITLE
Add approval forms to funds just like the other forms are added

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#2958]
Also rename "Approval form" to "Project approval form".

**Comment by fourthletter** [comment]
I still don't see the option to add an approval form to a round https://test-apply.hypha.app/admin/pages/939/edit/?next=/admin/funds/round/%3Fform-state%3Dopen%26o%3D-3

**Comment by sandeepsajan0** [comment]
@fourthletter We decided to keep it with funds and labs only not with the round(because it is global and projects have nothing to do with rounds). You can see it in a fund and if you'll change it in the fund it will directly reflect there in PAF approval process.
cc @frjo 

**What [this](https://github.com/HyphaApp/hypha/pull/2966) PR contains:**  It makes the ProjectApprovalForm implementation with Funds and Labs similar to the other forms so that all forms UI should be the same as shown in the below image(Add forms button).

<img width="880" alt="image" src="https://user-images.githubusercontent.com/23638629/189354245-cf4a3486-1a96-4118-ada0-ec01b1698fcb.png">

**Comment by fourthletter** [comment]
Thank you for clarifying! I see the add approval form option in Funds. 👍
