### ISSUE TITLE
Move DRAFT submissions on funds to current round

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#3105]
### User Story

When a draft is created, the date should be when it was submitted. When submissions are submitted to a 'round,' the date of the submission needs to align within the same timeframe of a particular 'round.'  Drafts created outside this timeframe should be moved to the current round on submission.

**Comment by frjo** [comment]
The date is already fixed in an earlier issue. This issue is about attaching submissions on funds to the current round.

If someone created a draft six month ago but does not submit in until now it will currently belong to the round that was active six month ago. OTF want to change this. Instead a draft that getting submitted should be attched to the current fund.

**Comment by fourthletter** [comment]
I tested and it works great. Thank you! 💥 

A draft was created on Jan 30 and submitted on Jan 31. The submission appears in the most recent open fund, not the fund where the submission was created/drafted.

![image](https://user-images.githubusercontent.com/20019656/215719398-482c2c80-ca27-4e94-88e2-e92db38b04f8.png)
