### ISSUE TITLE
On staff dashboard rename "Active invoices" to "Invoices awaiting your review"

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#3177]
Staff only interest in invoices are when they need to review them.

**Comment by theskumar** [comment]
Could we name it "Pending Review"?

**Comment by theskumar** [comment]
@abhiXII to review it before we do dev.

**Comment by abhiXII** [comment]
Seems like it's called `active invoices` because invoices that do not need staff review but are currently in process are also listed here. 

<img width="1304" alt="image" src="https://user-images.githubusercontent.com/124244361/220151299-28a3d21e-846e-4496-89b9-f82f8585ab39.png">

We COULD change it to show only the invoices that need staff approval or some action

**Comment by frjo** [comment]
@abhiXII Yes, I think we should do that. Unless a invoice needs a review it should not show on staff dashboard.

The dashboard is for items that need an action, review, approval, etc.
