### ISSUE TITLE
Requesting contract corrections as an applicant

### ISSUE THREAD

**Issue by abhiXII** [HyphaApp/hypha#3334]
When an applicant clicks on `corrections/amendments` option they go to communications page with Application selected by default. I think it should be either all or the person who the communication should go to? 
This can avoid errors of unknowingly missing out on sending correction requests to the right person

![Image](https://user-images.githubusercontent.com/124244361/229825107-eebdadcd-2901-4a6e-8ffe-0d0522702944.png)

![Image](https://user-images.githubusercontent.com/124244361/229825190-a952f07c-08b9-46ec-bbb8-05e5688fbd9e.png)

**Comment by sandeepsajan0** [comment]
@frjo I think this should be a general setting (in both submissions and projects) for applicant users. Because It doesn't make sense that applicants' comment is visible to the applicants only.  Right now, the first option is the default for applicants and others except staff.
We have this kind of setting for staff [here](https://github.com/HyphaApp/hypha/blob/main/hypha/apply/activity/forms.py#L27), we can have similar for applicants as well.

**Comment by frjo** [comment]
The "Applicant(s)" choice will actually make it visible for the applicant and staff. So it is the option they almost always should pick.

We have another issue pointing out that this naming make sense for staff but not for applicants.

**Comment by sandeepsajan0** [comment]
I think we can close this one as well?
