### ISSUE TITLE
What is the "Partner" roles used for in practice?

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#3455]
The Partner roles was added quite some time back and I believe it then was intended to expand with more features.

Today I think it is only ever used as a way to add extra applicants to a submission? Is this correct?

**Comment by fourthletter** [comment]
The 'partner' role is currently used for several purposes. 

- add extra applicants to a submission
- add vendor (does not have applicant status) to a submission because they are providing the applicant a service like security audit, digital security training, or design support
- add host organization (does not have applicant status) to a submission because it's an institution like university hosting a fellow, and they are reviewing the submission to see if it's a good fit for their institution

**Comment by frjo** [comment]
What does "applicant status" entail in this situation. Other permissions in Hypha?

**Comment by frjo** [comment]
Do we e.g. need to have separate comment permissions for applicant an partner? 

In another issue it sounds like you wanted partners and applicants to see the same comments.

If no special permissions are needed I suggest we remove the partner role and give them the applicant role instead. Then instead of adding "Partners" to a submission you would be adding "Extra applicant"/"Sub applicant" or whatever you want to call them.

You have on many occasions spoken about how complex you find the user roles to be so having on less to worry about would be good I think.

**Comment by fourthletter** [comment]
On July 13 we considered removing the partner role entirely since this role essentially has all the functionalities of the applicant user group. We need to be intentional with this approach because there are many users currently with the partner use role, and OTF relies on this user role.

**Comment by frjo** [comment]
We start with https://github.com/HyphaApp/hypha/issues/3487 and https://github.com/HyphaApp/hypha/issues/2868

**Comment by wes-otf** [comment]
Closing this issue as partners (in an OTF context) are typically seen as Vendors this far (#3737). ie. A lab/fund will assign vendors as partners to work with applicants & be able to communicate via the comms tab. The functionality added in #3699 made this a feasible option for vendors.
