### ISSUE TITLE
Submit BOTH review and opinion to an application

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#3525]
### Description

As a user when staff 'agree' to a review they are unable to submit a written review. The staff reviewer is unable to 'agree' and submit a written review for a concept note. When staff submits a 'disagree' opinion, they are still able to submit a review.

### Proposed Solution

Staff should be able to do both actions 1) 'agree' as in to submit an opinion and 2) submit a written review if they choose to.

## Staff is given the option to agree or disagree with a review
![image](https://github.com/HyphaApp/hypha/assets/20019656/11b96d55-5c68-40ea-a346-2453f022f8c6)

## Staff 'agree' and could no longer submit their own written review
![image](https://github.com/HyphaApp/hypha/assets/20019656/d0d19c72-5f6a-4269-a70c-9871d2d4f772)

**Comment by frjo** [comment]
To me the bug is that you can submit a review after leaving a "disagree" option. This feature was developed as an alternative to submitting a full review.

What is the point of submitting an opinion plus a full review? How is it used? How should it be displayed in Hypha. How should the review scores be calculated?
