### ISSUE TITLE
Previewing rounds in Wagtail admin result in error

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#3559]
NoReverseMatch 'users' is not a registered namespace

**Comment by fourthletter** [comment]
When applications are **drafted** for an existing Round1, those applications are assigned to a particular Lead1. When those applications are **submitted** during a later date to Round2 and Lead2, those applications may still be associated with Lead1. The expected behavior is that the application should be associated with Lead2.

**Comment by frjo** [comment]
@fourthletter Please create a separate issue for that, they are not related.

**Comment by fourthletter** [comment]
### Description

We could only preview Rounds, and not Fund or forms. We could also only preview Rounds on this user interface (image 1) and not directly on the form (image 2)

## Image 1
![image](https://github.com/HyphaApp/hypha/assets/20019656/27ded4e6-1ac8-4d7a-8e46-20e4918798ee)

## Image 2 
![image](https://github.com/HyphaApp/hypha/assets/20019656/350bace5-9a7c-4072-9115-7dfa61642290)

**Comment by frjo** [comment]
One and the same.

**Comment by theskumar** [comment]
close this now? @frjo
