### ISSUE TITLE
Status bar labels are frequently misaligned/off-center

### ISSUE THREAD

**Issue by wes-otf** [HyphaApp/hypha#3669]
When looking at the progress/stage indicator of an application, the titles are frequently misaligned and not consistent.

The following are screenshots with lines drawn through the center of the stage points to better show this misalignment. Some are better than others:

![Screenshot 2023-11-28 at 11 00 36 AM](https://github.com/HyphaApp/hypha/assets/145372368/ea243d6d-2a96-4220-8c91-0b0b702fe46e)
-------------
![Screenshot 2023-11-28 at 10 54 00 AM(1)](https://github.com/HyphaApp/hypha/assets/145372368/21a4b198-6b75-42aa-9a72-5acfb722f085)
-------------
![Screenshot 2023-11-28 at 10 54 46 AM](https://github.com/HyphaApp/hypha/assets/145372368/6b3487ae-0af0-4815-8d24-2213cd1a2fd4)
-------------

Definitely not a mission-critical bug but would still be nice for appearance.

**Comment by frjo** [comment]
This needs to be rebuilt with simpler HTML structure  modern css, like "grid" e.g.

The current versions tries to pixel adjust things and it fails for different fonts, different screen sizes and different zoom levels.

Since we are using "system-ui" fonts it will look different on masOS vs Windows etc.
