### ISSUE TITLE
Editing a submission leads to duplicate entries in the "revisions" section, one of which causes an error

### ISSUE THREAD

**Issue by wes-otf** [HyphaApp/hypha#3709]
When a proposal has been edited, it will sometimes create a duplicate entry in the revisions section. One of these duplicates (typically the oldest entry) will result in an error of `invalid literal for int() with base 10: ''` at [hypha/apply/funds/blocks.py](https://github.com/HyphaApp/hypha/blob/main/hypha/apply/funds/blocks.py#L200) when attempting to open it, due to a lack of a `duration` field.

**Comment by wes-otf** [comment]
Working to get more details on this

**Comment by wes-otf** [comment]
I believe this has to do with Concept & Proposal workflows, specifically with what's in the forms for such. Sometimes for the initial proposal revision (looking at IFF for example) will not contain a duration field, but all revisions after will despite it being a mandatory field in the form. 

Struggling to recreate it locally as it seems very field dependent but according to sentry this error was seen 17 times just this month.

So far, steps for recreating on test/live have been (needed role denoted by brackets):
1. [Applicant] Submit an application to a Concept/Proposal fund
2. [Staff] Approve the concept note
3. [Applicant] Submit a follow-up proposal
4. [Staff] Request more information
5. [Applicant] Edit & re-submit the application
6. [Staff] Finally, look at the revisions. One of them (normally the earliest) will cause an error.

**Comment by sandeepsajan0** [comment]
I think I found its root cause. I followed the above steps and got `JsonDecodeError...` but when I looked deeply I found this issue is because of empty data.
Last year we made some changes [in AccessFormData mixin's `render_answer` method](https://github.com/HyphaApp/hypha/blob/main/hypha/apply/funds/models/mixins.py#L289) to render questions even if there is no answer, previously we were just skipping those fields(including questions) and showing `-`. So for rendering the questions we pass the answer as an empty string `''` and it is handled in[ `serialize_no_response` method](https://github.com/HyphaApp/hypha/blob/main/hypha/apply/stream_forms/blocks.py#L84)(to use `-` in place of answers only) but in between it calls prepare data and for some blocks we have custom `prepare_data` that expects data to be in desired type. So sometimes it throws `invalid int...` error and sometimes `JsonDecode error...`
Ex:
In AddressFieldBlock, [it expects a json object](https://github.com/HyphaApp/hypha/blob/main/hypha/apply/funds/blocks.py#L101) so for no data it throws `JSONDecodeError`.
Similarly, [DurationBlock expects an Integer ](https://github.com/HyphaApp/hypha/blob/main/hypha/apply/funds/blocks.py#L195)and throws `invalid int..` error.

So, I think if we can just confirm the data(maybe its type too) in custom `prepare_data` methods, it should work fine. I'll try to create a PR soon for that.

**Comment by frjo** [comment]
@sandeepsajan0 Excellent digging! This is a small bug but one that I think is quite annoying to staff. Will be good to get it fixed.

**Comment by wes-otf** [comment]
@sandeepsajan0 this is fantastic work! was definitely driving me insane trying to track this down. thanks a ton for looking into it!
