### ISSUE TITLE
Can not set up 2FA, works in v5.3.1

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#3757]
`django.urls.exceptions.NoReverseMatch: 'two_factor' is not a registered namespace`

My guess is that we have a small hickup in the URLs after removing public.

We should add a test to make sure this does not get broken agin.

Replicate by going to your account page, click "Enable 2FA" and on the next page click "I've installed a 2FA App". Then you get the above error.

I notices that the 2FA pages need some margins as well. One example here:

<img width="499" alt="Skärmavbild 2024-02-07 kl  13 33 22" src="https://github.com/HyphaApp/hypha/assets/191392/51fccfa9-f705-401d-952a-8e38f21c63ec">

**Comment by frjo** [comment]
@theskumar Can you take a look at this?

**Comment by sandeepsajan0** [comment]
@frjo @theskumar I looked into it, it is happening because we have moved the `two_factor` url to [user's app](https://github.com/HyphaApp/hypha/commit/2db6a2743b9d29a791b37fb754188d803a77aba3#diff-29c594fee4f3a0f4fce30aea4512dfd68135c3ec7c328efe8ed8bd31bc7a604cR179). Although we took care of it in our code but whenever library's internal classes/methods try to call any url it creates issues.
I found these two places where the library is internally calling the urls: 1. [SetupView success_urls and qrcode_url (responsible for setup 2FA)](https://github.com/jazzband/django-two-factor-auth/blob/master/two_factor/views/core.py#L442) 2. [BackupTokensView success_url (responsible to generates codes)](https://github.com/jazzband/django-two-factor-auth/blob/master/two_factor/views/core.py#L650).

Now we have two solutions for this either we override every class/method that is calling a url internally or just move it out from user app to base urls.py. I think the second solution will be easy to maintain. What are your thoughts about it?

**Comment by frjo** [comment]
Move to base urls.py sounds a lot easier.

**Comment by theskumar** [comment]
@sandeepsajan0 thanks for looking into this. I agree with your second solution. Moving to root urls.py is the right way to go. I'll take of it.
