### ISSUE TITLE
Cookie popup enhancements

### ISSUE THREAD

**Issue by wes-otf** [HyphaApp/hypha#3925]
As OTF works to implement better policies around the GDPR, one of those is to improve the cookie pop-up. I think as we have lots of international adopters these changes would also benefit the overall community. A few changes that should take place:
 - [ ] A `Learn More` option be added to the existing options of `Decline` & `Accept` which (in the same pop-up) would give a brief explanation of all the cookies utilized by Hypha.
 - [ ] Out of the box (as far as I'm aware) Hypha utilizes only essential cookies. This doesn't require an opt-in, so the existing `Decline` & `Accept` can be removed as it could imply some other tracking is going on.
 - [ ] If an adopter does want to add analytics, a ~~configuration~~ wagtail variable should get set that would re-enable the `Decline` & `Accept` language (maybe using `Essential only` & `Accept all` instead), along with pulling `Learn More` verbiage from a custom ~~template~~ wagtail field that explain what the analytics cookies do and what third parties have access to it.
 - [ ] Ideally the user should be able to change these preferences later, maybe under the profile view?

Here's an example of what I imagine the `Learn More` aspect of the pop-up to function like, using an example from StackOverflow:
<img width="550" alt="Screenshot 2024-05-13 at 14 59 38" src="https://github.com/HyphaApp/hypha/assets/145372368/7089cec0-9a42-4726-8a76-647318629706">

<br>
Curious to hear thoughts!

**Comment by frjo** [comment]
Good initiative! This needs some work.

1. My overall goal would be to keep the cookie consent as small and unintrusive as possible. Just having one at all is annoying enough to the visitors.
2. Making the button text configurable is a good idea, you can also use translations for that.
3. The "Cookie consent message" field is richtext so links etc. can be added. But a specific "more info" link can be convenient to have. I think both the text and the url need to be configurable.
4. We should have a link in the footer to allow users to reopen the dialog and update the choice.
5. The cookieconsent setting should be saved in localStorage instead of in a cookie.

We also need documentation how to implement this so the buttons actually works when you add trackers.

On the OTF page I believe Matomo is always active regardless of what the users select, "Decline & Accept".
