### ISSUE TITLE
When Project Form is submitted by someone that isn't the lead, to do notification stays in lead's todo

### ISSUE THREAD

**Issue by wes-otf** [HyphaApp/hypha#3946]
If the Project Form is submitted by a user that isn't the project lead, the `Project ... is waiting for PAF submission` notification will remain in the lead's To-Do list despite the Project Form being submitted. This was done with no PAF Reviewers set so I wonder if it's related to #3881?

**Comment by wes-otf** [comment]
also the verbiage in the to do item should probably be changed from PAF to reflect the changes made in #3900

**Comment by sandeepsajan0** [comment]
@wes-otf Yes, you are right it is related to #3881. I tried to repopulate it, but it only happens when no Project Reviewer Roles are set and when I checked the code I found no task removal code. I have added it in #4026. 

I think renaming PAF to Project Form in UI, especially in todo and tasks requires another PR.
